# Generated by Django 5.1.3 on 2025-03-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
