# Generated by Django 5.1.3 on 2025-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
