# Generated by Django 5.1.3 on 2025-03-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0004_adminaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAccount',
        ),
    ]
