# Generated by Django 5.1.3 on 2025-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0007_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
