# Generated by Django 5.1.7 on 2025-04-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0010_remove_cart_product_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=5, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register')),
            ],
        ),
    ]
