# Generated by Django 5.1.7 on 2025-04-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0013_alter_admin_email_alter_products_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincommission',
            name='commission_date',
        ),
    ]
