# Generated by Django 5.1.7 on 2025-04-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0014_remove_admincommission_commission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
