# Generated by Django 5.1.7 on 2025-06-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0016_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='seller',
        ),
    ]
