# Generated by Django 5.1.7 on 2025-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0017_remove_payment_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
