# Generated by Django 5.1.7 on 2025-06-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroideryapp', '0018_feedback_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='embroideryapp.tbl_register'),
        ),
    ]
